# Generated by Django 4.2.1 on 2025-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FILTER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
