# Generated by Django 4.2.1 on 2025-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FILTER', '0002_generation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
