# Generated by Django 4.2.1 on 2025-01-06 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FILTER', '0004_alter_generation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.IntegerField(choices=[(0, 'Седан'), (1, 'Хэтчбек'), (2, 'Лифтбек'), (3, 'Универсал'), (4, 'Минивэн'), (5, 'Купе'), (6, 'Пикап'), (7, 'Кабриолет'), (8, 'Фургон'), (9, 'Внедорожник')])),
                ('engine', models.JSONField(choices=[('EngineType', ((0, 'Бензин'), (1, 'Дизель'), (2, 'Гибрид'), (3, 'Электро'))), ('BoostType', ((0, 'Турбированный'), (1, 'Атмосферный'))), ('EquipmentType', ((0, 'Газобаллонное оборудование'),))])),
                ('engine_capacity', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.001))),
                ('drive', models.IntegerField(choices=[(0, 'Передний'), (1, 'Задний'), (2, 'Полный')])),
                ('broken', models.IntegerField(choices=[(0, 'Не битые'), (1, 'Битые'), (2, 'Не на ходу')])),
                ('mileage', models.IntegerField(default=0, verbose_name=django.core.validators.MinValueValidator(0))),
                ('price', models.IntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=10000)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.brand')),
                ('generation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.generation')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.model')),
            ],
        ),
    ]
