# Generated by Django 4.2.1 on 2025-01-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FILTER', '0004_alter_generation_number'),
        ('ADS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='engine',
        ),
        migrations.AddField(
            model_name='ads',
            name='boost_type',
            field=models.IntegerField(choices=[(0, 'Не предусмотрен'), (1, 'Атмосферный'), (2, 'Турбированный')], null=True, verbose_name='Нагнетатель'),
        ),
        migrations.AddField(
            model_name='ads',
            name='engine_type',
            field=models.IntegerField(choices=[(0, 'Бензин'), (1, 'Дизель'), (2, 'Гибрид'), (3, 'Электро')], null=True, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='ads',
            name='equipment_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Газобаллонное оборудование')], null=True, verbose_name='Дополнительное оборудование'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='body',
            field=models.IntegerField(choices=[(0, 'Седан'), (1, 'Хэтчбек'), (2, 'Лифтбек'), (3, 'Универсал'), (4, 'Минивэн'), (5, 'Купе'), (6, 'Пикап'), (7, 'Кабриолет'), (8, 'Фургон'), (9, 'Внедорожник')], verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='broken',
            field=models.IntegerField(choices=[(0, 'Не битая'), (1, 'Битая'), (2, 'Не на ходу')], verbose_name='Битая'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='drive',
            field=models.IntegerField(choices=[(0, 'Передний'), (1, 'Задний'), (2, 'Полный')], verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='engine_capacity',
            field=models.FloatField(verbose_name='Объём двигателя'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.generation', verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
