# Generated by Django 4.2 on 2025-04-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name_plural': 'Bodies'},
        ),
        migrations.AlterModelOptions(
            name='broken',
            options={'verbose_name_plural': 'Broken'},
        ),
    ]
