# Generated by Django 4.2.1 on 2025-01-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0002_remove_ads_engine_ads_boost_type_ads_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='body',
            field=models.IntegerField(verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='boost_type',
            field=models.IntegerField(null=True, verbose_name='Наддув'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='broken',
            field=models.IntegerField(verbose_name='Битая'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='drive',
            field=models.IntegerField(verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='engine_type',
            field=models.IntegerField(null=True, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='equipment_type',
            field=models.IntegerField(null=True),
        ),
    ]
