# Generated by Django 4.2.1 on 2025-01-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0003_alter_ads_body_alter_ads_boost_type_alter_ads_broken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='equipment_type',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
