# Generated by Django 4.2 on 2025-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_options_alter_body_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
