# Generated by Django 4.2.1 on 2025-01-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0004_alter_ads_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='equipment_type',
        ),
    ]
