# Generated by Django 4.2.1 on 2025-01-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0006_body_boosttype_broken_drive_enginetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.body', verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='boost_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.boosttype', verbose_name='Наддув'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='broken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.broken', verbose_name='Битая'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.drive', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='engine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.enginetype', verbose_name='Двигатель'),
        ),
    ]
