# Generated by Django 4.2.1 on 2025-01-17 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FILTER', '0005_body_boosttype_broken_drive_enginetype'),
        ('ADS', '0007_alter_ads_body_alter_ads_boost_type_alter_ads_broken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.body', verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='boost_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.boosttype', verbose_name='Наддув'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='broken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.broken', verbose_name='Битая'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.drive', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='engine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FILTER.enginetype', verbose_name='Двигатель'),
        ),
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.DeleteModel(
            name='BoostType',
        ),
        migrations.DeleteModel(
            name='Broken',
        ),
        migrations.DeleteModel(
            name='Drive',
        ),
        migrations.DeleteModel(
            name='EngineType',
        ),
    ]
