# Generated by Django 4.2.1 on 2025-01-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0008_alter_ads_body_alter_ads_boost_type_alter_ads_broken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=10000, verbose_name='Комментарий')),
            ],
        ),
    ]
