# Generated by Django 4.2.1 on 2025-01-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0009_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
