# Generated by Django 4.2.1 on 2025-01-30 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0010_rename_comment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ADS.comments', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
