# Generated by Django 4.2.1 on 2025-01-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0011_alter_ads_comment_alter_comments_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ADS/photos')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADS.ads')),
            ],
        ),
    ]
