# Generated by Django 4.2.1 on 2025-01-31 09:42

import ADS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADS', '0012_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to=ADS.models.path_and_rename),
        ),
    ]
